version: "3.3"

services:
  cs:
    image: kmallea/csgo:latest
    volumes:
        - ./server.cfg:/home/steam/csgo-dedicated/server.cfg
    restart: always
    environment:
      PORT: 55655
      TV_PORT: 55666
      AUTHKEY: '745807093EEF0616C117A88AC586CCDC'
      SRCDS_PORT: 55655
      SRCDS_TV_PORT: 55666
      SRCDS_TOKEN: '745807093EEF0616C117A88AC586CCDC'
      SRCDS_FPSMAX: 300
      SRCDS_TICKRATE: 128
      SRCDS_MAXPLAYERS: 14
      SRCDS_STARTMAP: "de_dust2"
      SRCDS_REGION: 3
      SRCDS_MAPGROUP: "mg_active"
      SRCDS_GAMETYPE: 0
      SRCDS_GAMEMODE: 1
      SRCDS_HOSTNAME: "CVD server"
      SRCDS_WORKSHOP_START_MAP: 0
      SRCDS_HOST_WORKSHOP_COLLECTION: 0
      SRCDS_WORKSHOP_AUTHKEY: ""
      ADDITIONAL_ARGS: ""

