version: "3.9"

services:
  cs:
    image: cm2network/csgo:latest
    volumes:
      - server.cfg:/home/steam/csgo-dedicated/server.cfg
    restart: always
    environment:
      SRCDS_PORT: 27016
      SRCDS_TV_PORT: 27021
      SRCDS_TOKEN:
      SRCDS_FPSMAX: 300
      SRCDS_TICKRATE: 128
      SRCDS_MAXPLAYERS: 14
      SRCDS_STARTMAP: "de_dust2"
      SRCDS_REGION: 3
      SRCDS_MAPGROUP: "mg_active"
      SRCDS_GAMETYPE: 0
      SRCDS_GAMEMODE: 1
      SRCDS_HOSTNAME: "New CSGO Server" (first launch only)
      SRCDS_WORKSHOP_START_MAP: 0
      SRCDS_HOST_WORKSHOP_COLLECTION: 0
      SRCDS_WORKSHOP_AUTHKEY: "" (required to use host_workshop_map)
      ADDITIONAL_ARGS: ""
